export const Colors = {
  background:    '#F5F6F8',
  surface:       '#FFFFFF',
  card:          '#FFFFFF',
  accent:        '#196699',
  accentDark:    '#1B3A5C',
  text:          '#1A1A2E',
  textSecondary: '#5A6178',
  textMuted:     '#93A0AB',
  border:        '#DDDEE9',
  success:       '#0F6A5B',
  danger:        '#A32D2D',
  warning:       '#B07D18',
  navy:          '#1B3A5C',
  dangerSoft:    '#FDEAEA',
  successSoft:   '#E0F4EF',
};
